#~~set_prefix colorful_dir_icon~~#
    if   [[ "$PWD" == ~ ]]; then dir_icon='#~~char home~~#'
    elif [[ "$PWD" == ~/Code ]]; then dir_icon='#~~char code~~#'
    elif [[ "$PWD" == ~/Music ]]; then dir_icon='#~~char music~~#'
    elif [[ "$PWD" == ~/Documents ]]; then dir_icon='#~~char documents~~#'
    elif [[ "$PWD" == ~/Downloads ]]; then dir_icon='#~~char downloads~~#'
    elif [[ "$PWD" == ~/Desktop ]]; then dir_icon='#~~char desktop~~#'
    elif [[ "$PWD" == ~/Pictures ]]; then dir_icon='#~~char pictures~~#'
    elif [[ "$PWD" == ~/Videos ]]; then dir_icon='#~~char videos~~#'
    elif [[ "$PWD" == ~/.config ]]; then dir_icon='#~~char config~~#'
    elif [[ "$PWD" == / ]]; then dir_icon='#~~char root~~#'
    elif [[ "$PWD" == /usr ]]; then dir_icon='#~~char usr~~#'
    elif [[ ! -w "$PWD" ]]; then dir_icon='#~~char locked~~#'
    elif [[ "$PWD":t == .* ]]; then dir_icon='#~~char hidden~~#'
    elif test ! "$PWD"/*(NDY1); then dir_icon='#~~char empty~~#'
    else dir_icon='#~~char default~~#'
    fi#~~set_prefix colorful_precmd~~#