# vim: set syntax=kitty:
# Font {{{
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

box_drawing_scale 0.001, 0.5, 1.5, 2
# }}}
# Window {{{
remember_window_size  no
initial_window_width  1000
initial_window_height 500
# }}}
# Tab Bar {{{
active_tab_background   #19c3e0
inactive_tab_background #a4b9bd
# }}}
# Bell Sound {{{
enable_audio_bell yes
bell_path /usr/share/sounds/freedesktop/stereo/bell.oga
# }}}
# Colors {{{
# background #3F3F3F <-- bg without transparency
background #074473
background_opacity 0.25
# black {{{
color0 #2E3436
color8 #555753
# }}}
# red {{{
color1 #CC0000
color9 #EF2929
# }}}
# green {{{
color2  #4E9A06
color10 #8AE234
# }}}
# yellow {{{
color3  #E3BA09
color11 #FCE94F
# }}}
# blue {{{
color4  #3465A4
color12 #729FCF
# }}}
# magenta {{{
color5  #75507B
color13 #AD7FA8
# }}}
# cyan {{{
color6  #06989A
color14 #34E2E2
# }}}
# white {{{
color7  #D3D7CF
color15 #EEEEEC
# }}}
# }}}
# Advanced {{{
editor vim
# }}}
# Keyboard Shortcuts {{{
map kitty_mod+s paste_from_selection
map kitty_mod+y combine : goto_layout tall : launch --location=vsplit --bias=30 cava : previous_window

map ctrl+enter send_text all \x1b[27;5;13~

map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right

map kitty_mod+m next_layout

map kitty_mod+alt+enter new_tab
map kitty_mod+alt+h previous_tab
map kitty_mod+alt+l next_tab

map kitty_mod+alt+. move_tab_forward
map kitty_mod+alt+, move_tab_backward
# }}}
